### ISSUE TITLE
OpenTracing Proxy Auto Configuration

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/opentracing-toolbox#336]
## Detailed Description

Define a module providing a Spring Boot Auto Configuration for `opentracing-proxy`.

## Context

- Integration into Spring Boot ecosystem
- Coupling to Spring is encapsulated in separate module/artifact
- Zalando Conventions over Configuration, i.e. ready to use
- Customizability via Spring Boot configuration and beans

### Module
- `opentracing-proxy` (parent) :heavy_check_mark: 
  - `opentracing-proxy` :heavy_check_mark: 
  - `opentracing-proxy-autoconfigure` :new: 

### Auto Configuration
- `OpenTracingProxyAutoConfiguration`
- `@Primary Tracer proxyTracer(Tracer)`?
- Find registered `Plugin` implementations (inject `@Order`ed list)
- Register pre-defined plugins via config (unless a plugin is registered manually?), e.g.

```yaml
opentracing.proxy:
  log-correlation:
    enabled: true # default?
    baggage:
      - flow_id
  auto-tagging:
    enabled: true # default?
    baggage:
      - flow_id
  tag-propagation:
    enabled: true # default?
    tags:
      - customer_id
      - payment_method
      - sales_channel
      - country
      - language
```
